---
services:
  python-api:
    build:
      context: ./python
    ports:
      - "8000:8000"
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - RABBITMQ_HOST

  nginx:
    image: nginx:1.26.2
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - python-api

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer1:
    build:
      context: ./api1
    depends_on:
      - rabbitmq

  consumer2:
    build:
      context: ./api2
    depends_on:
      - rabbitmq

configs:
  nginx:
    file: ./nginx.conf

volumes:
  db-data:
